In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    "Price" : [100,200,300]
})
print(type(df["Price"].values))

<class 'numpy.ndarray'>


In [ ]:
countries = ["nepal","india",21,True]

In [9]:
import numpy as np

In [38]:
salary_array = np.array([1000,2000,3000])
print(salary_array.ndim)
print(salary_array.shape)
print(salary_array.size)
print(salary_array[-1])

data = np.array([
    [10,1000], 
    [20,2000],
    [30,3000], 
    [40,3000], 
    [50,3000], 
    [60,3000]
])
print(data[:,1])
print(data[0:3])
print(data[0,1])
print(data.ndim) 
print(data.shape)
print(data.size)

price = np.array([10,20,30,40.6])
print(price.dtype)

price2 = np.array([10.5,20.3,30.5])
print(price2.dtype)

1
(3,)
3
3000
[1000 2000 3000 3000 3000 3000]
[[  10 1000]
 [  20 2000]
 [  30 3000]]
1000
2
(6, 2)
12
float64
float64


In [41]:
numbers = np.array([1,2,3,4,5])
results = numbers * 10
print(results)

[10 20 30 40 50]


In [40]:
numbers = [1,2,3,4,5]
# output ---> [10,20,30,40,50]
results = []
for num in numbers:
    results.append(num*10)
print(results)

[10, 20, 30, 40, 50]
