In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("datasets/daraz_dataset.csv")
df.head()
df.shape
df.columns
df.dtypes
df["Age"]
# df["Age"] = pd.to_numeric(df["Age"],errors="coerce")

numeric_columns = [
"Age", 
"Quantity",
"UnitPrice",
"DiscountPercent",
"TotalAmount", 
"Rating"
]

for column in numeric_columns:
   df[column] = pd.to_numeric(df[column],errors="coerce")

df.isnull().sum()
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())

features = ["Age","Quantity","UnitPrice","DiscountPercent"]
target = "TotalAmount"

#Super features store garne X , target store garne Y banaunu
X = df[features] 
y = df[target]

type(X)
type(y)

X = X.to_numpy()
y = y.to_numpy()

type(X)
type(y)

# X.shape
# X.ndim
# X.dtype
# X.nbytes
X[0]
X[:,0]
X[:,3]
print(X[X[:,0]>30])

print(np.min(X[:,0]))
df

[[5.2000e+01 2.0000e+00 3.3418e+04 2.0000e+01]
 [3.1000e+01 2.0000e+00 4.6053e+04 1.5000e+01]
 [4.2000e+01 5.0000e+00 1.7635e+04 0.0000e+00]
 ...
 [3.9000e+01 4.0000e+00 3.0055e+04 2.0000e+01]
 [4.8000e+01 3.0000e+00 4.7942e+04 2.0000e+01]
 [3.5000e+01 4.0000e+00 5.7070e+03 5.0000e+00]]
nan


,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,NaN,Male,Nepalgunj,Sports,Football,3.12024,NaN,NaN,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52.0,Female,Pokhara,Electronics,Bluetooth Speaker,2.00000,33418.0,20.0,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31.0,Female,Lalitpur,Books,Python Basics,2.00000,46053.0,15.0,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42.0,Male,Chitwan,Home,Chair,5.00000,17635.0,0.0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32.0,Male,Dharan,Groceries,Tea,1.00000,3303.0,5.0,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48.0,Male,Nepalgunj,Electronics,Smart Watch,3.00000,47942.0,20.0,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35.0,Female,Bhaktapur,Electronics,Power Bank,4.00000,5707.0,5.0,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27.0,Female,Itahari,Books,Data Science 101,1.00000,48890.0,0.0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27.0,Female,Dharan,Beauty,Shampoo,5.00000,2468.0,10.0,11106.00,IME Pay,2,Returned


In [7]:
age = np.array([10,20,30])
roll_no = np.array([11,22,33])
print(age)
print(roll_no)
# type(age)
students = np.array([
    [20,30,40], 
    [10,12,14]
])

print(students)

[10 20 30]
[11 22 33]
[[20 30 40]
 [10 12 14]]


In [16]:
student_datas = np.array([[12,90],
[14,80],
[16,50]
])
# print(student_datas)
weights = np.array([
    [10],
    [2]]
)

prediction = np.dot(student_datas,weights)
print(prediction)

[[300]
 [300]
 [260]]
